panda:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  pd_controller:
    type: franka_arm_ros/PDController
    arm_id: panda
    joint_names:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
